#!/usr/bin/env bash

source cluster.conf

## Two color codes.
SY=$'\x1b[33;1m'
NC=$'\x1b[0m'

# Here we create a firewall rule for our SEDGE VM. It will feature a http(s) server and a DNS server:
echo "${SY}Adding firewall rules.${NC}"
[[ $(gcloud compute firewall-rules list --project $PROJECT | grep sedge) ]] || \
    gcloud compute firewall-rules create sedge \
           --allow tcp:80 tcp:443 tcp:53 udp:53 \
           --target-tags sedge \
           --project $PROJECT \
           --description "Basic rules for sedge services"

# Create SEDGE instance:
echo "${SY}Creating sedge-01 VM.${NC}"
gcloud compute instances create sedge-01 \
       --project $PROJECT \
       --machine-type $SEDGE_MACHINE_TYPE \
       --image centos-6 \
       --zone $ZONE \
       --network default \
       --can-ip-forward \
       --tags sedge \
       --scopes compute-rw storage-rw

# Create and assign a static local IP (route) to be used by the internal DNS server.
echo "${SY}Creating route for static local IP.${NC}"
gcloud compute routes create ip-10-10-0-1 \
       --next-hop-instance sedge-01 \
       --next-hop-instance-zone $ZONE \
       --destination-range 10.10.0.1/32

# Create two disks for SEDGE to use:
echo "${SY}Creatind two disks for data and docker.${NC}"
## This will be used for data (e.g jenkins)
gcloud compute disks create sedge-01-data-volume \
       --project $PROJECT \
       --size 50GiB \
       --zone $ZONE \
       --quiet
## This will be used for docker images:
gcloud compute disks create sedge-01-docker-volume \
       --project $PROJECT \
       --size 50GiB \
       --zone $ZONE \
       --quiet

# Attach disks to SEDGE:
echo "${SY}Attaching disks to sedge-01.${NC}"
gcloud compute instances attach-disk sedge-01 \
       --disk sedge-01-data-volume \
       --device-name sedge-01-data-volume \
       --project $PROJECT \
       --zone $ZONE
gcloud compute instances attach-disk sedge-01 \
       --disk sedge-01-docker-volume \
       --device-name sedge-01-docker-volume \
       --project $PROJECT \
       --zone $ZONE

# Prepare SEDGE.
echo "${SY}Preparing sedge-01. Installing apps, creating filesystems, etc.${NC}"
## First we lift CentOS' restrictions to ssh logins and non-interactive sudos:
gcloud compute ssh sedge-01 \
       --zone $ZONE \
       --project $PROJECT \
       --ssh-flag="-tt" \
       --ssh-flag "-o ConnectTimeout=360" \
       --command "sudo sed -e 's/\(Defaults.*requiretty\)/#\1/' -i /etc/sudoers"
gcloud compute ssh sedge-01 \
       --zone $ZONE \
       --project $PROJECT \
       --command "\
sudo sed -e 's/PermitRootLogin no/PermitRootLogin yes/' -i /etc/ssh/sshd_config; \
sudo service sshd restart; \
sudo mkdir /root/.ssh/;"

## Now let's format our disks, install and configure our software:
gcloud compute ssh root@sedge-01 \
       --zone $ZONE \
       --project $PROJECT \
       --command "\
yum install -y http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm; \
yum install -y git; \
cd /root; git clone https://github.com/scalding-io/hadoop-on-gce.git; \
cd hadoop-on-gce; git checkout alternate-configuration; \
/root/hadoop-on-gce/sedge.conf.d/boostrap; "
