#!/bin/bash
#
# custom_dns Set custom hostname and DNS
#
# chkconfig: 345 99 10
# description: Set custom hostname and DNS, added by Marios @ scalding.io
#
### BEGIN INIT INFO
# Provides: $custom_dns
# Short-Description: Set FQDN and DNS
# Description: Set FQDN and DNS
### END INIT INFO

# Source function library.
. /etc/init.d/functions

start() {
    echo -n "Setting hostname and DNS: "
    echo 'nameserver 10.10.0.1' > /etc/resolv.conf
    CUR_HNAME="$(hostname | sed -e 's/\..*//')"
    CUR_IP="$(hostname -I)"
    sed -i '/Google/d' /etc/hosts
    sed -i '/'$CUR_HNAME'/d' /etc/hosts
    echo "$CUR_IP $CUR_HNAME.cluster.30ohm.com $CUR_HNAME" >> /etc/hosts
    hostname $CUR_HNAME.cluster.30ohm.com
    return 0
}

stop() {
    return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        echo "Nothing to report."
        ;;
    restart|reload)
        start
        ;;
    *)
        echo "Usage: <servicename> {start|stop|restart}"
        exit 1
        ;;
esac
exit $?
